// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import "./globals.css";

// export const metadata = {
//   title: "Quant Research Platform",
//   description: "Research-grade quantitative analysis system",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="h-screen bg-gray-900 text-gray-100">
//         <div className="flex h-full">
//           {/* Sidebar */}
//          <aside className="w-64 bg-gray-900 border-r border-gray-800 p-5 flex flex-col">
//   <div className="mb-8">
//     <h2 className="text-xl font-bold tracking-wide">Quant Lab</h2>
//     <p className="text-xs text-gray-400 mt-1">
//       Research Platform
//     </p>
//   </div>

//   <nav className="space-y-2 text-sm">
//     <NavItem label="Market Data" href="/market" />
//     <NavItem label="Indicator Lab" href="/indicators" />
//     <NavItem label="Strategy Builder" href="/stratergy" />
//     <NavItem label="Backtesting" href="/backtest" />
//     <NavItem label="Trading Mentor" href="/mentor" />
//   </nav>

//   <div className="mt-auto text-xs text-gray-500">
//     MVP Prototype
//   </div>
// </aside>


//           {/* Main content */}
//           <main className="flex-1 p-6 overflow-auto">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }

// function NavItem({ label, href }: { label: string; href: string }) {
//   return (
//     <a
//       href={href}
//       className="block px-3 py-2 rounded-md hover:bg-gray-800 transition text-gray-300 hover:text-white"
//     >
//       {label}
//     </a>
//   );
// }






// import "./globals.css";
// // import { usePathname } from "next/navigation";
// // import Sidebar from "@/components/Sidebar";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const pathname = usePathname();
//   const isLandingPage = pathname === "/";

//   return (
//     <html lang="en" className="bg-black">
//       <body className="bg-black text-white">
//         <div className="flex min-h-screen">
//           {!isLandingPage && <Sidebar />}

//           <main className="flex-1 overflow-x-hidden">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }


import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black">
      <body className="bg-black text-white min-h-screen">
        {children}
      </body>
    </html>
  );
}

